# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

#Controls when the workflow will run
on:
  #Triggers the workflow on push or pull request events but only for main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#A Workflow is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #This worlflow contains a single job called "build"
  build:
    #The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    #Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    #Checks out your repostiroy under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #running the Lint process as üart of our CI pipeline
    - run: npm ci
    - run: npx eslint --fix-dry-run index.js
    - run: npm run build --if-present
    - run: npm test
